# Vue Trillo demo Azure pipeline
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

stages:
  - stage: build
    displayName: Build Vue front end
    jobs:
      - job: frontend
        pool:
          vmImage: "ubuntu 16.04"
        steps:
          - bash: npm install
          - bash: npm run test
          - bash: npm run build
  - stage: deploy
    displayName: Deploy Trillo demo to Github pages
    jobs:
      - job: githubpages
        steps:
          - bash: echo "This is test of deployments"
