# Vue Trillo demo Azure pipeline
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: build
    jobs:
    - job: febuild
      container: node:10-alpine
      steps:
      - bash: npm install
      - bash: npm run build
      - bash: npm run test
  - stage: deploy
    jobs:
      - job: githubdeploy
        displayName: Deploy to Github pages
        container: alpine:3.9
        steps:
          - bash: echo "This is test of deployments"